package ru.otus.hw.les12;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Objects;
import java.util.UUID;

/**
 * Клиент банка
 */
public class Client {
    private final String name;
    private final int age;

    //Добавлен для идентификации клиента, так как подразумеваю что name теоретически может меняться
    //хотя setter сейчас не реализован, без setter можно было hashCode и equals реализовывать на name
    //можно вместо UUID использовать Int, но тогда нужно реализовывать генератор Id
    private final UUID id;
    private final ArrayList<Account> accounts;

    /**
     * Создать клиента
     *
     * @param id   Id клиента
     * @param name Имя клиента
     * @param age  Возраст клиента
     */
    private Client(UUID id, String name, int age) {
        this.name = name;
        this.age = age;
        this.id = id;
        this.accounts = new ArrayList<>();
    }

    /**
     * Создать клиента с автосгенерированным Id
     *
     * @param name Имя клиента
     * @param age  Возраст клиента
     * @return Новый клиент
     */
    public static Client createClientWithAutogeneratedId(String name, int age) {
        var id = UUID.randomUUID();
        return new Client(id, name, age);
    }


    /**
     * Получить Id клиента
     *
     * @return Id клиента
     */
    public UUID getId() {
        return id;
    }

    /**
     * Получить имя клиента
     *
     * @return имя клиента
     */
    public String getName() {
        return name;
    }

    /**
     * Получить возраст клиента
     *
     * @return возраст клиента
     */
    public int getAge() {
        return age;
    }

    /**
     * Получить список счетов
     *
     * @return счета клиента
     */
    public Collection<Account> getAccounts() {
        return accounts;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Client client = (Client) o;
        return Objects.equals(id, client.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        StringBuilder accountsStr = new StringBuilder();
        for (var account : getAccounts()) {
            accountsStr.append(", ").append(account);
        }
        if (!accountsStr.toString().equalsIgnoreCase("")) {
            accountsStr = new StringBuilder("{" + accountsStr.substring(2) + "}");
        }
        return "Client{" +
                "name='" + getName() + '\'' +
                ", age=" + getAge() +
                ", id=" + getId() +
                ", accounts={" + accountsStr +
                "}}";
    }
}
